package Tests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.testng.annotations.AfterMethod;

import java.util.*;

public class TestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterMethod
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test() {
    driver.get("https://topiframe.nsc-tech.ru/");
    driver.manage().window().setSize(new Dimension(1886, 1013));
    driver.findElement(By.cssSelector(".ListIcons_list-item__3mXQy:nth-child(1) path:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".ListIcons_list-item__3mXQy:nth-child(7) .ListIcons_list-item-icon__2GPEF")).click();
    driver.findElement(By.cssSelector(".Tabs_tab___fA6r:nth-child(3) > .Service_break-word__kCdwU")).click();
    driver.findElement(By.id("inputPan-olif3")).click();
    driver.findElement(By.id("inputPan-h63r3")).sendKeys("2200 0000 0000 0004");
    driver.findElement(By.id("inputExpDate-u9clo")).click();
    driver.findElement(By.id("inputExpDate-egdpu")).sendKeys("12/24");
    driver.findElement(By.id("inputCardHolder-tmcvu")).click();
    driver.findElement(By.id("inputCardHolder-4dscq")).sendKeys("SER IVAN");
    driver.findElement(By.id("inputCVC-2awjv")).click();
    driver.findElement(By.id("inputCVC-jt9q4")).sendKeys("123");
    driver.findElement(By.name("cheques.email")).click();
    driver.findElement(By.name("cheques.email")).sendKeys("s.ivanov@ruru.ru");
    driver.findElement(By.name("captcha")).click();
    driver.findElement(By.name("captcha")).sendKeys("3332");
    driver.findElement(By.id("checkbox__offer")).click();
    driver.findElement(By.cssSelector(".Button_text__1Mw40")).click();
    js.executeScript("window.scrollTo(0,0)");
  }
}
